'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

function read(relativePath) {
  return fs.readFileSync(path.join(__dirname, '..', relativePath), 'utf8');
}

test('API routes expose authenticated Unit resolution and creation options while Commit owns Unit writes', () => {
  const routes = read('routes/api.js');
  assert.match(routes, /router\.get\('\/units\/creation-options',[\s\S]*requireApiAuth[\s\S]*requireUnitApiAccess/);
  assert.match(routes, /router\.post\('\/units\/resolve',[\s\S]*requireApiAuth[\s\S]*requireUnitApiAccess/);
  assert.match(routes, /router\.post\('\/units\/commit',[\s\S]*requireApiAuth[\s\S]*requireUnitApiAccess/);
  assert.doesNotMatch(routes, /router\.post\('\/units',\s*requireApiAuth,\s*requireUnitApiAccess,\s*apiUnitController\.createUnit\)/);
});

test('Unit creation preserves BWTDallas Asset Tag authority and existing canonical create path', () => {
  const intake = read('services/apiUnitIntake.js');
  assert.match(intake, /ASSET_TAG_NOT_ASSIGNABLE/);
  assert.match(intake, /Asset Tags are generated by BWTDallas/);
  assert.match(intake, /techUnitModel\.createTechUnit\(formData, userId/);
  assert.match(intake, /techUnitModel\.getDisplayAssetTag\(assetNumber\)/);
});

test('Unit resolution uses current BWTDallas duplicate/identifier matching and never assumes a duplicate', () => {
  const intake = read('services/apiUnitIntake.js');
  assert.match(intake, /findDuplicateUnitsForForm/);
  assert.match(intake, /resolveUnitIdentity/);
  assert.match(intake, /UNIT_DUPLICATE_REVIEW_REQUIRED/);
  assert.match(intake, /DUPLICATE_MATCH_CONFIRMATION_REQUIRED/);
  assert.doesNotMatch(intake, /assumeExistingTechUnitFromDuplicateMatch/);
  assert.doesNotMatch(intake, /createIntentionalDuplicateTechUnitWithConnection/);
});

test('Tool-created Unit records use Unit History audit events with the authenticated tool source', () => {
  const intake = read('services/apiUnitIntake.js');
  assert.match(intake, /buildUnitFormAuditEvent/);
  assert.match(intake, /source: `api_\$\{toolSource\}`/);
  assert.match(intake, /toolSource/);
});

test('Unit creation remains an internal Commit primitive rather than a standalone Tool write endpoint', () => {
  const routes = read('routes/api.js');
  const intake = read('services/apiUnitIntake.js');
  assert.doesNotMatch(routes, /router\.post\('\/units',\s*requireApiAuth,\s*requireUnitApiAccess,\s*apiUnitController\.createUnit\);/);
  assert.match(intake, /async function createUnitForCommit/);
  assert.doesNotMatch(intake, /async function createUnit\(\{ body = \{\}, userId, toolSource \}\)/);
  assert.doesNotMatch(intake, /ingestScalarInventory/);
  assert.doesNotMatch(intake, /unit_tool_observations/);
});


test('Tool-created Units can retain technician-entered Previous Memory and Previous Storage without inventing new component storage', () => {
  const intake = read('services/apiUnitIntake.js');
  assert.match(intake, /previous_memory/);
  assert.match(intake, /previous_storage/);
  assert.match(intake, /previousRamGb: previousMemory\.totalGb/);
  assert.match(intake, /previousMemoryModules: previousMemory\.modules/);
  assert.match(intake, /previousStorageGb: previousStorage\.totalGb/);
  assert.match(intake, /previousStorageDevices: previousStorage\.devices/);
  assert.match(intake, /tech_user_input_via_tool/);
  assert.match(intake, /previous_component_options/);
  assert.match(intake, /memory_install_types/);
  assert.match(intake, /storage_types/);
});

test('manual Previous Storage input remains limited to fields exposed by the normal technician form', () => {
  const intake = read('services/apiUnitIntake.js');
  const previousStorageBlock = intake.match(/function normalizePreviousStorage[\s\S]*?\n}\n\nfunction normalizeIdentity/)?.[0] || '';
  assert.match(previousStorageBlock, /storage_type_config_value_id/);
  assert.doesNotMatch(previousStorageBlock, /manufacturer_name|model_number|firmware_version|wipe_status_config_value_id/);
  assert.match(previousStorageBlock, /serialNumber: ''/);
});

test('new Tool-created Units keep Unit Category as a processing prerequisite rather than weakening the schema', () => {
  const intake = read('services/apiUnitIntake.js');
  const audit = read('scripts/auditApiUnitIntake.js');
  const preflight = read('services/apiUnitPreflight.js');

  assert.match(preflight, /UNIT_CATEGORY_REQUIRED/);
  assert.match(preflight, /Tool processing prerequisite/);
  assert.match(intake, /UNIT_CATEGORY_REQUIRED/);
  assert.match(audit, /new Tool-created Units require unit_category_config_value_id as a processing prerequisite/);
  assert.doesNotMatch(audit, /ALTER TABLE units MODIFY COLUMN unit_category_config_value_id/);
});

