'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

function read(relativePath) {
  return fs.readFileSync(path.join(__dirname, '..', relativePath), 'utf8');
}

test('API routes expose authenticated Unit resolution and creation options while Commit owns Unit writes', () => {
  const routes = read('routes/api.js');
  assert.match(routes, /router\.get\('\/units\/creation-options',[\s\S]*requireApiAuth[\s\S]*requireUnitApiAccess/);
  assert.match(routes, /router\.post\('\/units\/resolve',[\s\S]*requireApiAuth[\s\S]*requireUnitApiAccess/);
  assert.match(routes, /router\.post\('\/units\/commit',[\s\S]*requireApiAuth[\s\S]*requireUnitApiAccess/);
  assert.doesNotMatch(routes, /router\.post\('\/units',\s*requireApiAuth,\s*requireUnitApiAccess,\s*apiUnitController\.createUnit\)/);
});

test('Unit creation preserves BWTDallas Asset Tag authority and existing canonical create path', () => {
  const intake = read('services/apiUnitIntake.js');
  assert.match(intake, /ASSET_TAG_NOT_ASSIGNABLE/);
  assert.match(intake, /Asset Tags are generated by BWTDallas/);
  assert.match(intake, /techUnitModel\.createTechUnit\(formData, userId/);
  assert.match(intake, /techUnitModel\.getDisplayAssetTag\(assetNumber\)/);
});

test('Unit resolution uses current BWTDallas duplicate/identifier matching and never assumes a duplicate', () => {
  const intake = read('services/apiUnitIntake.js');
  assert.match(intake, /findDuplicateUnitsForForm/);
  assert.match(intake, /resolveUnitIdentity/);
  assert.match(intake, /UNIT_DUPLICATE_REVIEW_REQUIRED/);
  assert.match(intake, /DUPLICATE_MATCH_CONFIRMATION_REQUIRED/);
  assert.doesNotMatch(intake, /assumeExistingTechUnitFromDuplicateMatch/);
  assert.doesNotMatch(intake, /createIntentionalDuplicateTechUnitWithConnection/);
});

test('Tool-created Unit records use Unit History audit events with the authenticated tool source', () => {
  const intake = read('services/apiUnitIntake.js');
  assert.match(intake, /buildUnitFormAuditEvent/);
  assert.match(intake, /source: `api_\$\{toolSource\}`/);
  assert.match(intake, /toolSource/);
});

test('Unit creation remains an internal Commit primitive rather than a standalone Tool write endpoint', () => {
  const routes = read('routes/api.js');
  const intake = read('services/apiUnitIntake.js');
  assert.doesNotMatch(routes, /router\.post\('\/units',\s*requireApiAuth,\s*requireUnitApiAccess,\s*apiUnitController\.createUnit\);/);
  assert.match(intake, /async function createUnitForCommit/);
  assert.doesNotMatch(intake, /async function createUnit\(\{ body = \{\}, userId, toolSource \}\)/);
  assert.doesNotMatch(intake, /ingestScalarInventory/);
  assert.doesNotMatch(intake, /unit_tool_observations/);
});
