CREATE TABLE IF NOT EXISTS unit_outcomes (
  unit_outcome_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  unit_id BIGINT UNSIGNED NOT NULL,
  outcome_code VARCHAR(20) NOT NULL,
  outcome_notes VARCHAR(500) NULL,
  approval_status_code VARCHAR(30) NOT NULL DEFAULT 'not_requested',
  is_current TINYINT(1) NOT NULL DEFAULT 1,
  selected_by_user_id BIGINT UNSIGNED NULL,
  selected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approval_requested_by_user_id BIGINT UNSIGNED NULL,
  approval_requested_at TIMESTAMP NULL DEFAULT NULL,
  approval_request_notes VARCHAR(1000) NULL,
  approved_by_user_id BIGINT UNSIGNED NULL,
  approved_at TIMESTAMP NULL DEFAULT NULL,
  approval_notes VARCHAR(1000) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (unit_outcome_id),
  KEY idx_unit_outcomes_unit_current (unit_id, is_current),
  KEY idx_unit_outcomes_outcome_current (outcome_code, is_current),
  KEY idx_unit_outcomes_approval_status (approval_status_code, is_current),
  KEY idx_unit_outcomes_selected_at (selected_at),
  KEY idx_unit_outcomes_selected_by (selected_by_user_id),
  KEY idx_unit_outcomes_requested_by (approval_requested_by_user_id),
  KEY idx_unit_outcomes_approved_by (approved_by_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
